# Generated by Django 2.2.9 on 2020-01-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.TextField(verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('desc', models.TextField(verbose_name='제품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('count', models.PositiveIntegerField(verbose_name='남은 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Account', verbose_name='거래처')),
            ],
        ),
    ]
